#pragma once
#include <drivers/usb/xhci_common.h>
#include <xlibc/xassert.h>
#include <kernel.h>

typedef struct __packed__ xhci_transfer_request_block {
    u64 parameter; // trb-specific parameter
    u32 status; // status information
    union {
        struct __packed__ {
            u32 cycle_bit   : 1;
            u32 rsvd0       : 9;
            u32 trb_type    : 6;
            u32 rsvd1       : 16;
        };
        u32 control; // control bits
    };
} xhci_trb_t;

STATIC_ASSERT(sizeof(xhci_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_command_completion_transfer_request_block {
    u64 command_trb_pointer;
    struct __packed__ {
        u32 rsvd0           : 24;
        u32 completion_code : 8;
    };
    struct __packed__ {
        u32 cycle_bit       : 1;
        u32 rsvd1           : 9;
        u32 trb_type        : 6;
        u32 vfid            : 8;
        u32 slot_id         : 8;
    };
} xhci_command_completion_trb_t;

STATIC_ASSERT(sizeof(xhci_command_completion_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_disable_slot_command_request_block {
    u64 rsvd0;
    u32 rsvd1;
    struct __packed__ {
        u32 cycle_bit   : 1;
        u32 rsvd2       : 9;
        u32 trb_type    : 6;
        u32 rsvd3       : 8;
        u32 slot_id     : 8;
    };
} xhci_disable_slot_command_trb_t;

STATIC_ASSERT(sizeof(xhci_disable_slot_command_trb_t) == sizeof(u32) * 4);

typedef struct xhci_address_device_request_block {
    u64 input_context_physical_base;
    u32 rsvd;
    struct {
        u32 cycle_bit   : 1;
        u32 rsvd1       : 8;

        /*
            Block Set Address Request (BSR). When this flag is set to ‘0’ the Address Device Command shall
            generate a USB SET_ADDRESS request to the device. When this flag is set to ‘1’ the Address
            Device Command shall not generate a USB SET_ADDRESS request. Refer to section 4.6.5 for
            more information on the use of this flag.
        */
        u32 bsr        : 1; // Block Set Address Request bit
        
        u32 trb_type   : 6;
        u32 rsvd2      : 8;
        u32 slot_id    : 8;
    };
} xhci_address_device_command_trb_t;

STATIC_ASSERT(sizeof(xhci_address_device_command_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 4.11.2.2 Figure 4-14 SETUP Data, the Parameter Component of Setup Stage TRB (page 211)
*/
typedef struct __packed__ xhci_device_request_packet {
    union __packed__ {
        struct __packed__ {
            /*
                Recipient Values:
                0       = Device
                1       = Interface
                2       = Endpoint
                3       = Other
                4..31   = Reserved
            */
            u8 recipient           : 5;

            /*
                Type Values:
                0       = Standard
                1       = Class
                2       = Vendor
                3       = Reserved
            */
            u8 type                : 2;

            /*
                Direction Values:
                0       = Host to Device
                1       = Device to Host
            */
            u8 transfer_direction   : 1;
        };

        u8 bRequestType;
    };

    // Desired request
    u8 bRequest;

    // Request-specific
    u16 wValue;

    // Request-specific
    u16 wIndex;

    // Number of bytes to transfer if in data phase
    u16 wLength;
} xhci_device_request_packet_t;

STATIC_ASSERT(sizeof(xhci_device_request_packet_t) == 8);


/*
// xHci Spec Section 6.4.1.2.1 Setup Stage TRB (page 468)

A Setup Stage TRB is created by system software to initiate a USB Setup packet
on a control endpoint. Refer to section 3.2.9 for more information on Setup
Stage TRBs and the operation of control endpoints. Also refer to section 8.5.3 in
the USB2 spec. for a description of “Control Transfers”.
*/
typedef struct __packed__ xhci_setup_stage_transfer_request_block {
    xhci_device_request_packet_t request_packet;
    
    struct __packed__ {
        // Always 8
        u32 trb_transfer_length  : 17;

        // Reserved
        u32 rsvd0                : 5;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target   : 10;
    };

    struct __packed__ {
        // This bit is used to mark the Enqueue point of a Transfer ring
        u32 cycle_bit       : 1;

        // Reserved
        u32 rsvd1           : 4;

        /*
            Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB
            completes, the Host Controller shall notify the system of the completion by placing an
            Event TRB on the Event ring and sending an interrupt at the next interrupt threshold.
            Refer to section 4.10.4.
        */
        u32 ioc             : 1;

        /*
            Immediate Data (IDT). This bit shall be set to ‘1’ in a Setup Stage TRB.
            It specifies that the Parameter component of this TRB contains Setup Data.
        */
        u32 idt             : 1;

        // Reserved
        u32 rsvd2           : 3;

        /*
            TRB Type. This field is set to Setup Stage TRB type.
            Refer to Table 6-91 for the definition of the Type TRB IDs.
        */
        u32 trb_type        : 6;

        /*
            Transfer Type (TRT). This field indicates the type and direction of the control transfer.
            Value Definition
            0 No Data Stage
            1 Reserved
            2 OUT Data Stage
            3 IN Data Stage
            Refer to section 4.11.2.2 for more information on the use of TRT.
        */
        u32 trt            : 2;

        // Reserved
        u32 rsvd3          : 14;
    };
} xhci_setup_stage_trb_t;

STATIC_ASSERT(sizeof(xhci_setup_stage_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 6.4.1.2.2 Data Stage TRB Figure 6-10: Data Stage TRB (page 470)

A Data Stage TRB is used generate the Data stage transaction of a USB Control
transfer. Refer to section 3.2.9 for more information on Control transfers and
the operation of control endpoints. Also refer to section 8.5.3 in the USB2 spec.
for a description of “Control Transfers”.
*/
typedef struct __packed__ xhci_data_stage_transfer_request_block {
    /*
        Data Buffer Pointer Hi and Lo. These fields represent the 64-bit address of the Data
        buffer area for this transaction.

        The memory structure referenced by this physical memory pointer is allowed to begin on
        a byte address boundary. However, user may find other alignments, such as 64-byte or
        128-byte alignments, to be more efficient and provide better performance.
    */
    u64 data_buffer;

    struct __packed__ {
        /*
            TRB Transfer Length. For an OUT, this field is the number of data bytes the xHC will send
            during the execution of this TRB.

            For an IN, the initial value of the field identifies the size of the data buffer referenced
            by the Data Buffer Pointer, i.e. the number of bytes the host expects the endpoint to deliver.
            Valid values are 1 to 64K.
        */
        u32 trb_transfer_length  : 17;

        /*
            TD Size. This field provides an indicator of the number of packets remaining in the TD.
            Refer to section 4.11.2.4 for how this value is calculated.
        */
        u32 td_size             : 5;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target  : 10;
    };

    struct __packed__ {
        // This bit is used to mark the Enqueue point of a Transfer ring
        u32 cycle_bit       : 1;

        /*
            Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the
            next TRB before saving the endpoint state. Refer to section 4.12.3 for more information.
        */
        u32 ent            : 1;

        /*
            Interrupt-on Short Packet (ISP). If this flag is ‘1’ and a Short Packet is encountered
            for this TRB (i.e., less than the amount specified in TRB Transfer Length), then a
            Transfer Event TRB shall be generated with its Completion Code set to Short Packet.
            The TRB Transfer Length field in the Transfer Event TRB shall reflect the residual
            number of bytes not transferred into the associated data buffer. In either case, when
            a Short Packet is encountered, the TRB shall be retired without error and the xHC shall
            advance to the Status Stage TD.

            Note: if the ISP and IOC flags are both ‘1’ and a Short Packet is detected, then only one
            Transfer Event TRB shall be queued to the Event Ring. Also refer to section 4.10.1.1.
        */
        u32 isp            : 1;

        /*
            No Snoop (NS). When set to ‘1’, the xHC is permitted to set the No Snoop bit in the
            Requester Attributes of the PCIe transactions it initiates if the PCIe configuration
            Enable No Snoop flag is also set.
            
            When cleared to ‘0’, the xHC is not permitted to set PCIe packet No Snoop Requester
            Attribute. Refer to section 4.18.1 for more information.

            NOTE: If software sets this bit, then it is responsible for maintaining cache consistency.
        */
        u32 no_snoop        : 1;

        /*
            Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring.
            A Data Stage TD is defined as a Data Stage TRB followed by zero or more Normal TRBs.
            The Chain bit is used to identify a multi-TRB Data Stage TD.
            
            The Chain bit is always ‘0’ in the last TRB of a Data Stage TD.
        */
        u32 chain          : 1;

        /*
            Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB
            completes, the Host Controller shall notify the system of the completion by placing an
            Event TRB on the Event ring and sending an interrupt at the next interrupt threshold.
            Refer to section 4.10.4.
        */
        u32 ioc             : 1;

        /*
            Immediate Data (IDT). This bit shall be set to ‘1’ in a Setup Stage TRB.
            It specifies that the Parameter component of this TRB contains Setup Data.
        */
        u32 idt            : 1;

        // Reserved
        u32 rsvd0          : 3;

        /*
            TRB Type. This field is set to Setup Stage TRB type.
            Refer to Table 6-91 for the definition of the Type TRB IDs.
        */
        u32 trb_type        : 6;

        /*
            Direction (DIR). This bit indicates the direction of the data transfer as defined in the
            Data State TRB Direction column of Table 7. If cleared to ‘0’, the data stage transfer
            direction is OUT (Write Data).
            
            If set to ‘1’, the data stage transfer direction is IN (Read Data).
            Refer to section 4.11.2.2 for more information on the use of DIR.
        */
        u32 dir            : 1;

        // Reserved
        u32 rsvd1          : 15;
    };
} xhci_data_stage_trb_t;

STATIC_ASSERT(sizeof(xhci_data_stage_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 6.4.1.2.3 Status Stage TRB Figure 6-11: Status Stage TRB (page 472).

A Status Stage TRB is used to generate the Status stage transaction of a USB
Control transfer. Refer to section 3.2.9 for more information on Control transfers
and the operation of control endpoints.
*/
typedef struct __packed__ xhci_status_stage_transfer_request_block {
    // Reserved
    u64 rsvd0;

    struct __packed__ {
        // Reserved
        u32 rsvd1              : 22;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target  : 10;
    };

    struct __packed__ {
        // This bit is used to mark the Enqueue point of a Transfer ring
        u32 cycle_bit       : 1;

        /*
            Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the
            next TRB before saving the endpoint state. Refer to section 4.12.3 for more information.
        */
        u32 ent            : 1;

        // Reserved
        u32 rsvd2          : 2;

        /*
            Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring.
            A Data Stage TD is defined as a Data Stage TRB followed by zero or more Normal TRBs.
            The Chain bit is used to identify a multi-TRB Data Stage TD.
            
            The Chain bit is always ‘0’ in the last TRB of a Data Stage TD.
        */
        u32 chain          : 1;

        /*
            Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB
            completes, the Host Controller shall notify the system of the completion by placing an
            Event TRB on the Event ring and sending an interrupt at the next interrupt threshold.
            Refer to section 4.10.4.
        */
        u32 ioc            : 1;

        // Reserved
        u32 rsvd3          : 4;

        /*
            TRB Type. This field is set to Setup Stage TRB type.
            Refer to Table 6-91 for the definition of the Type TRB IDs.
        */
        u32 trb_type        : 6;

        /*
            Direction (DIR). This bit indicates the direction of the data transfer as defined in the
            Data State TRB Direction column of Table 7. If cleared to ‘0’, the data stage transfer
            direction is OUT (Write Data).
            
            If set to ‘1’, the data stage transfer direction is IN (Read Data).
            Refer to section 4.11.2.2 for more information on the use of DIR.
        */
        u32 dir            : 1;

        // Reserved
        u32 rsvd4          : 15;
    };
} xhci_status_stage_trb_t;

STATIC_ASSERT(sizeof(xhci_status_stage_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_transfer_completion_request_block {
    u64 transfer_trb_pointer;
    struct __packed__ {
        u32 transfer_length : 24;
        u32 completion_code : 8;
    };
    struct __packed__ {
        u32 cycle_bit   : 1;
        u32 rsvd1       : 1;
        u32 event_data  : 1;
        u32 rsvd2       : 7;
        u32 trb_type    : 6;
        u32 endpoint_id : 5;
        u32 rsvd3       : 3;
        u32 slot_id     : 8;
    };
} xhci_transfer_completion_trb_t;

STATIC_ASSERT(sizeof(xhci_transfer_completion_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_port_status_change_request_block {
    struct __packed__ {
        u32 rsvd0   : 24;
        u32 port_id : 8;
    };
    u32 rsvd1;
    struct __packed__ {
        u32 rsvd2           : 24;
        u32 completion_code : 8;
    };
    struct __packed__ {
        u32 cycle_bit  : 1;
        u32 rsvd3      : 9;
        u32 trb_type   : 6;
        u32 rsvd4      : 16;
    };
} xhci_port_status_change_trb_t;

STATIC_ASSERT(sizeof(xhci_port_status_change_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_evaluate_context_command_request_block {
    u64 input_context_physical_base;
    u32 rsvd0;
    struct __packed__ {
        u32 cycle_bit  : 1;
        u32 rsvd1      : 8;
        u32 rsvd2      : 1;
        u32 trb_type   : 6;
        u32 rsvd3      : 8;
        u32 slot_id    : 8;
    };
} xhci_evaluate_context_command_trb_t;

STATIC_ASSERT(sizeof(xhci_evaluate_context_command_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_configure_endpoint_command_request_block {
    u64 input_context_physical_base;
    u32 rsvd0;
    struct __packed__ {
        u32 cycle_bit    : 1;
        u32 rsvd1        : 8;
        u32 deconfigure  : 1;
        u32 trb_type     : 6;
        u32 rsvd3        : 8;
        u32 slot_id      : 8;
    };
} xhci_configure_endpoint_command_trb_t;

STATIC_ASSERT(sizeof(xhci_configure_endpoint_command_trb_t) == sizeof(u32) * 4);

typedef struct __packed__ xhci_normal_request_block {
    u64 data_buffer_physical_base;
    union __packed__ {
        struct __packed__ {
            u32 trb_transfer_length  : 17;
            u32 td_size             : 5;
            u32 interrupter_target  : 10;
        };
        u32 dword1;
    };
    struct __packed__ {
        // This bit is used to mark the Enqueue point of a Transfer ring
        u32 cycle_bit       : 1;

        /*
            Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the
            next TRB before saving the endpoint state. Refer to section 4.12.3 for more information.
        */
        u32 ent            : 1;

        /*
            Interrupt-on Short Packet (ISP). If this flag is ‘1’ and a Short Packet is encountered
            for this TRB (i.e., less than the amount specified in TRB Transfer Length), then a
            Transfer Event TRB shall be generated with its Completion Code set to Short Packet.
            The TRB Transfer Length field in the Transfer Event TRB shall reflect the residual
            number of bytes not transferred into the associated data buffer. In either case, when
            a Short Packet is encountered, the TRB shall be retired without error and the xHC shall
            advance to the Status Stage TD.

            Note: if the ISP and IOC flags are both ‘1’ and a Short Packet is detected, then only one
            Transfer Event TRB shall be queued to the Event Ring. Also refer to section 4.10.1.1.
        */
        u32 isp            : 1;

        /*
            No Snoop (NS). When set to ‘1’, the xHC is permitted to set the No Snoop bit in the
            Requester Attributes of the PCIe transactions it initiates if the PCIe configuration
            Enable No Snoop flag is also set.
            
            When cleared to ‘0’, the xHC is not permitted to set PCIe packet No Snoop Requester
            Attribute. Refer to section 4.18.1 for more information.

            NOTE: If software sets this bit, then it is responsible for maintaining cache consistency.
        */
        u32 no_snoop        : 1;

        /*
            Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring.
            A Data Stage TD is defined as a Data Stage TRB followed by zero or more Normal TRBs.
            The Chain bit is used to identify a multi-TRB Data Stage TD.
            
            The Chain bit is always ‘0’ in the last TRB of a Data Stage TD.
        */
        u32 chain          : 1;

        /*
            Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB
            completes, the Host Controller shall notify the system of the completion by placing an
            Event TRB on the Event ring and sending an interrupt at the next interrupt threshold.
            Refer to section 4.10.4.
        */
        u32 ioc             : 1;

        /*
            Immediate Data (IDT). This bit shall be set to ‘1’ in a Setup Stage TRB.
            It specifies that the Parameter component of this TRB contains Setup Data.
        */
        u32 idt            : 1;

        // Reserved
        u32 rsvd0          : 2;

        /*
            Block Event Interrupt (BEI). If this bit is set to '1' and IOC = '1', then the
            Transfer Event generated by IOC shall not assert an interrupt to the host at the
            next interrupt threshold. Refer to section 4.17.5.
        */
        u32 bei            : 1;

        /*
            TRB Type. This field is set to Setup Stage TRB type.
            Refer to Table 6-91 for the definition of the Type TRB IDs.
        */
        u32 trb_type        : 6;

        /*
            Direction (DIR). This bit indicates the direction of the data transfer as defined in the
            Data State TRB Direction column of Table 7. If cleared to ‘0’, the data stage transfer
            direction is OUT (Write Data).
            
            If set to ‘1’, the data stage transfer direction is IN (Read Data).
            Refer to section 4.11.2.2 for more information on the use of DIR.
        */
        u32 dir            : 1;

        // Reserved
        u32 rsvd1          : 15;
    };
} xhci_normal_trb_t;

STATIC_ASSERT(sizeof(xhci_normal_trb_t) == sizeof(u32) * 4);

typedef struct xhci_stop_endpoint_command_request_block {
    u64 rsvd0;
    u32 rsvd1;
    struct {
        u32 cycle_bit    : 1;
        u32 rsvd2        : 8;
        u32 suspend      : 1;
        u32 trb_type     : 6;
        u32 endpoint_id  : 5;
        u32 rsvd3        : 3;
        u32 slot_id      : 8;
    };
} xhci_stop_endpoint_command_trb_t;

STATIC_ASSERT(sizeof(xhci_stop_endpoint_command_trb_t) == sizeof(u32) * 4);

typedef struct xhci_reset_endpoint_command_request_block {
    u64 input_context_physical_base;
    u32 rsvd0;
    struct {
        u32 cycle_bit    : 1;
        u32 rsvd1        : 8;
        u32 tsp          : 1;
        u32 trb_type     : 6;
        u32 endpoint_id  : 5;
        u32 rsvd3        : 3;
        u32 slot_id      : 8;
    };
} xhci_reset_endpoint_command_trb_t;

STATIC_ASSERT(sizeof(xhci_reset_endpoint_command_trb_t) == sizeof(u32) * 4);

typedef struct xhci_set_tr_dequeue_ptr_command_request_block {
    u64 new_dequeue_ptr;
    u32 rsvd0;
    struct {
        u32 cycle_bit    : 1;
        u32 rsvd1        : 9;
        u32 trb_type     : 6;
        u32 endpoint_id  : 5;
        u32 rsvd2        : 3;
        u32 slot_id      : 8;
    };
} xhci_set_tr_dequeue_ptr_command_trb_t;

STATIC_ASSERT(sizeof(xhci_set_tr_dequeue_ptr_command_trb_t) == sizeof(u32) * 4);

const char* xhci_trb_completion_code_to_string(u8 completion_code);